[package]
name = "bootloader"
version = "0.1.0"
edition = "2021"
authors = ["陈功 <chengong456@qq.com>"]

[[bin]]
  name = "bootloader"
  test = false
  bench = false

[dependencies]
log = "0.4.20"
uefi = { version = "0.26.0", features = ["alloc"] }
uefi-services = "0.23.0"

