[build]
#target = "riscv64gc-unknown-none-elf"
target = "x86_64-unknown-none"
rustflags = ["-C", "link-arg=-no-pie"]

#[unstable]
#build-std = ["core", "compiler_builtins"]
#build-std-features = ["compiler-builtins-mem"]
