[build]
target = "riscv64gc-unknown-none-elf"
#target = "x86_64-unknown-none"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.riscv64gc-unknown-none-elf]
  runner = "qemu-system-riscv64 -machine virt -bios none -serial mon:stdio -nographic -kernel"

[target.x86_64-unknown-none]
  runner = "qemu-system-x86_64 -machine virt -bios none -serial mon:stdio -nographic -kernel"
